theme: minima
title: Covid Vaccine Candidates
author: koa-rod
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Simple overview of the vaccine candidates for covid.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  koa-rod # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
